"""empty message

Revision ID: 082ea7f519d7
Revises: 4bf68c2e5137
Create Date: 2026-03-31 03:06:59.684165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '082ea7f519d7'
down_revision = '4bf68c2e5137'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('zone', sa.String(length=120), nullable=False),
    sa.Column('equipment', sa.String(length=120), nullable=False),
    sa.Column('execution', sa.Text(), nullable=False),
    sa.Column('preparation', sa.Text(), nullable=False),
    sa.Column('routine_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['routine_id'], ['routine.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('routine', schema=None) as batch_op:
        batch_op.drop_column('exercises')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exercises', sa.TEXT(), autoincrement=False, nullable=False))

    op.drop_table('exercises')
    # ### end Alembic commands ###
