"""empty message

Revision ID: 5ae7ffbb4d36
Revises: 5b7466735082
Create Date: 2026-03-17 18:44:47.624372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ae7ffbb4d36'
down_revision = '5b7466735082'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['gym_class.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('routine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('muscle_group', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routine', schema=None) as batch_op:
        batch_op.drop_column('muscle_group')

    op.drop_table('favorites_classes')
    # ### end Alembic commands ###
