"""empty message

Revision ID: 9114c782980f
Revises: 7ee670473a4a
Create Date: 2026-03-18 04:40:58.268400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9114c782980f'
down_revision = '7ee670473a4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites_routines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('routine_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['routine_id'], ['routine.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('routine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('muscle_group', sa.String(length=50), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('fitness_goals', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('fitness_level', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('birth_date', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('avatar_url')
        batch_op.drop_column('phone')
        batch_op.drop_column('birth_date')
        batch_op.drop_column('fitness_level')
        batch_op.drop_column('fitness_goals')
        batch_op.drop_column('name')

    with op.batch_alter_table('routine', schema=None) as batch_op:
        batch_op.drop_column('muscle_group')

    op.drop_table('favorites_routines')
    # ### end Alembic commands ###
