"""empty message

Revision ID: daa0c1852b5a
Revises: 082ea7f519d7
Create Date: 2026-03-31 03:13:14.797400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daa0c1852b5a'
down_revision = '082ea7f519d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routine_exercises',
    sa.Column('routine_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['routine_id'], ['routine.id'], ),
    sa.PrimaryKeyConstraint('routine_id', 'exercise_id')
    )
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))
        batch_op.drop_constraint(batch_op.f('exercises_routine_id_fkey'), type_='foreignkey')
        batch_op.drop_column('routine_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('routine_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('exercises_routine_id_fkey'), 'routine', ['routine_id'], ['id'])
        batch_op.drop_column('image_url')

    op.drop_table('routine_exercises')
    # ### end Alembic commands ###
